package server

import (
	"context"
	"fmt"
	"log"
)

func (s Server) SeedIngredients() {
	// delete all ingredients first
	fmt.Println("Starting the seeding process of ingredients")
	err := s.store.DeleteAllIngredients(context.Background())
	if err != nil {
		log.Fatal("could not delete ingredients from db in seed process")
	}
	fmt.Println("Cleaned the ingredients table")
	ingredients := []string{
		"Salt",
		"Pepper",
		"Onion",
		"Garlic",
		"Olive oil",
		"Rape seed oil",
		"Wheat flour",
		"Water",
		"Egg",
		"Carrot",
		"Butter",
		"White sugar",
		"Potatoes",
		"Lemon",
		"Red bell pepper",
		"Parlsey",
		"Tomato",
		"Chopped tomatoes",
		"Minced beef",
		"Cucumber",
		"Chicken fillet",
		"Mushrooms",
		"Milk",
		"Red onion",
		"Fresh chilli pepper",
		"Leek",
		"Basmati rice",
		"Curry powder",
		"Oregano",
		"Spring onion",
		"Paprika",
		"Cherry tomatoes",
		"Fresh basil",
		"Yeast",
		"Margarine",
		"Apple",
		"Cream",
		"Fresh ginger",
		"Vegetable stock",
		"Soy sauce",
		"Bacon",
		"Lemon juice",
		"Grated cheese",
		"Tomato paste",
		"Dried thyme",
		"Green bell pepper",
		"Baking powder",
		"Green peas",
		"Rolled oats",
		"Broccoli",
		"Lime",
		"Feta cheese",
		"Cumin",
		"Breadcrumbs",
		"Pasta",
		"Mustard",
		"Rosemary",
		"Thyme",
		"Cinnamon",
		"Chives",
		"Dried chilli pepper",
		"Vanilla",
		"Chicken stock",
		"White wine",
		"Red wine",
		"Corn starch",
		"Dried basil",
		"Dill",
		"Corn",
		"White cabbage",
		"Bay leaves",
		"Chocolate",
		"Chicken breast",
		"Fresh coriander",
		"Grated parmesan",
		"Avocado",
		"Asparagus",
		"Vinegar",
		"Balsamic vinegar",
		"Baby spinach",
		"Cocoa powder",
		"Ketchup",
		"Flat parsley",
		"Orange",
		"Parmesan cheese",
		"Honey",
		"Salmon fillet",
		"Cauliflower",
		"Banana",
		"Pork tenderloin",
		"White pepper",
		"Cod fillet",
		"Pasta twists",
		"Sweet chilli sauce",
		"Sesame seeds",
		"Lettuce",
		"Sunflower oil",
		"Sugar",
		"Egg yolk",
		"Mint",
		"Shredder mozzarella cheese",
		"Zucchini",
		"Parsnip",
		"Chicken",
		"Wheat noodles",
		"Brown rice",
		"Egg whites",
		"Crisp green lettuce",
		"Plain yogurt",
		"Greek yogurt",
		"Pesto",
		"Turmeric",
		"Baking soda",
		"Wholemeal flour",
		"Pork chop",
		"Low fat mayonnaise",
		"Mayonnaise",
		"Spaghetti",
		"Sausages",
		"Turkey breast",
		"Lemon pepper",
		"Spinach",
		"Radish",
		"Food colouring",
		"Toast bread",
		"Cheese",
		"Strawberry",
		"Clove",
		"Burger buns",
		"Penne pasta",
		"Oil",
		"Tortillas",
		"Vanilla essence",
		"Artichoke",
		"Sliced smoked salmon",
		"Grounded ginger",
		"Raspberries",
		"Mozzarella",
		"Steak",
		"Tiger prawns",
		"Rice noodles",
		"Mango",
		"Corn flour",
		"Pork schnitzel",
		"Gherkins",
		"Peas",
		"Chorizo",
		"Barbecue sauce",
		"Pudding rice",
		"Coffee",
		"Cinnamon stick",
		"Risotto rice",
		"Worcestershire sauce",
		"Shredded beef",
		"Syrup",
		"Jalapeno chili pepper",
		"Beer",
		"Bread",
		"Rhubarb",
		"Lamb",
		"White chocolate",
		"Pork",
		"Duck breast",
		"Peanut butter",
		"Tabasco sauce",
		"Tofu",
		"Blueberry",
		"Pepperoni",
		"Bisquit",
	}
	dismissed := 0
	for _, ingredient := range ingredients {
		err := s.store.CreateIngredient(context.Background(), ingredient)
		if err != nil {
			fmt.Printf("failed to create ingredient %s\n", ingredient)
			dismissed++
		}
	}
	fmt.Printf("Seeded %d ingredients\n", len(ingredients)-dismissed)
}
